---
- hosts: all
  remote_user: root
  tasks:  
    - name: Ensure python is installed
      register: result
      raw: apt-get -y install python
      when:
        - ansible_pkg_mgr == 'apt'
      changed_when: "result.rc == 2"
      failed_when: "{{ result.rc not in [0, 2] }}"
