---
- hosts: webservers
  remote_user: root
  tasks:
  - name: Install apache2
    apt: name=apache2
  - name: Install apache2-php5
    package: name=libapache2-mod-php state=present
  - name: Install php-cli
    package: name=php-cli state=present
  - name: Install php-mcrypt
    package: name=php-mcrypt state=present
  - name: Install php-gd
    package: name=php-gd state=present
  - name: Install php-mysql
    package: name=php-mysql state=present
  - name: Install mysqlserver
    package: name=mysql-server state=present
