---
# This will install nagios

#- name: install nagios
#  yum: pkg={{ item }} state=present
#  with_items:
#   - nagios
#   - nagios-plugins
#   - nagios-plugins-nrpe
#   - nagios-plugins-ping
#   - nagios-plugins-ssh
#   - nagios-plugins-http
#   - nagios-plugins-mysql
#   - nagios-devel
#  notify: restart httpd
- name: install nagios prerequisites
  yum: pkg={{ item }} state=present
  with_items:
   - gcc
   - glibc
   - glibc
   - glibc-common
   - gd
   - gd-devel
   - make
   - net-snmp
   - openssl-devel
   - xinetd
   - unzip

#- name: install nagios
#  shell:  yum --enablerepo=epel -y install nagios nagios-plugins-{ping,disk,users,procs,load,swap,ssh,http,nrpe,mysql}
#  notify: restart httpd

- name: create nagios config dir
  file: path=/etc/nagios/ansible-managed state=directory

- name: create nagios localhost monitoring dir
  file: path=/etc/nagios/objects state=directory

- name: configure nagios
  copy: src=nagios.cfg dest=/etc/nagios/nagios.cfg
  notify: restart nagios

- name: configure localhost monitoring
  copy: src=localhost.cfg dest=/etc/nagios/objects/localhost.cfg
  notify: restart nagios

- name: configure nagios services
  copy: src=ansible-managed-services.cfg dest=/etc/nagios/

- name: create the nagios object files
  template: src={{ item + ".j2" }}
            dest=/etc/nagios/ansible-managed/{{ item }}
  with_items:
    - webservers.cfg
    - dbservers.cfg
    - lbservers.cfg
  notify: restart nagios

- name: start nagios
  service: name=nagios state=started enabled=yes
